#!/bin/bash
# Bash wrappers for docker run commands
convert(){
	docker run --rm \
                --user $UID:$UID \
		-v $PWD:/downloads \
		crea/util \
		convert "$@"
}

pdftk(){
	docker run --rm \
                --user $UID:$UID \
		-v $PWD:/downloads \
		crea/util \
		pdftk "$@"
}

youtube-dl(){
	docker run --rm \
                --user $UID:$UID \
                -v $PWD:/downloads \
		crea/util \
		youtube-dl "$@"
}

ffmpeg(){
	docker run --rm \
                --user $UID:$UID \
		-v $PWD:/downloads \
		crea/util \
		ffmpeg "$@"
}
